### ISSUE TITLE
Revisit the problem of automatic type casting

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#10]
Original thread: https://github.com/AdeptLanguage/Adept/discussions/165

I encountered this again today.

```
func main() void {
    a int = 2
    x double = 4.5
    b int = 3
    y double = 3.5
    if a*x < b*y, print("foo")
}
```

It will refuse to compile. I will need to cast a and b to double explicitly. You could see how ugly the code would be.

p/s: I'm still using Adept 2.x compiler.

**Comment by IsaacShelton** [comment]
Yes, it is a little ugly
```
func main() void {
    a int = 2
    x double = 4.5
    b int = 3
    y double = 3.5
    if a as double * x < b as double * y, print("foo")
}
```
```
func main() void {
    a int = 2
    x double = 4.5
    b int = 3
    y double = 3.5
    if cast double a * x < cast double b * y, print("foo")
}
```
As long as no information is lost during the conversion, I do think maybe this should be allowed.

For example, the above could work, but if `a` and `b` were ulongs instead it would still required manual casting since information could be lost.

I will investigate more of the pros/cons of this, but I don't see why (at the very least) a minimal version could be included to improve the situation you describe.

**Comment by ghost** [comment]
Instead of a compilation error, what do you think about a warning? I don't think it's required to do manual casting even for ulongs.

**Comment by IsaacShelton** [comment]
After some more thinking, I'm starting to agree with you on this. Since losing precision is kind of the entire point of a floating-point value after all. Also there isn't really a sensible alternative even when you care about the information loss, so nothing is really lost by having it automatic.

So yeah there's not really a case where losing information would matter, since floating-point values are meant to be inaccurate, and out of range values are perfectly represented as positive or negative infinity, so I'm starting to think maybe they should just coerce after all.

This would probably have to only apply to math expressions though, since otherwise passing integer values could incorrectly coerce to floating-point function parameters which could cause undesired behaviors.

**Comment by ghost** [comment]
Please backport the new behavior to Adept 2.x if it's possible. Thank you.

**Comment by IsaacShelton** [comment]
I've backported this improvement, and it should be available in the latest nightly shortly :tada:
