### ISSUE TITLE
Will you release your own C compiler?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#11]
From what you are doing it seems you are implementing a C compiler!

**Comment by IsaacShelton** [comment]
Yes, the Adept 3.x compiler will also be a C compiler.

To start, it will only be used for headers, but there are also plans of having the ability to include regular C files as well at some point.

For example of using headers, the following will work:

printf.h
```
#ifndef PRINTF_H_INCLUDED
#define PRINTF_H_INCLUDED

int printf(const char *const format, ...);

#endif // PRINTF_H_INCLUDED
```

main.adept
```
func main {
    printf(c"Hello World!\n")
}
```

**Comment by ghost** [comment]
What I actually had in mind when I posted this question is something like adeptcc, in the same sense of Pelles C and TCC: taking C source code and producing binary. It's kind of a standalone C compiler that has nothing to do with the Adept language. Or maybe it can use the Adept source code as a form of intermediate language before producing the final binary.

**Comment by IsaacShelton** [comment]
Yes it won't be a C compiler in the `tcc`-sense. It will be fully integrated into the main compiler and share the same machinery and build system. So yes like you mentioned, it will share the same intermediate language as Adept.

Adept code and C code will be treated the same during compilation.

The Adept compiler could be used separately as a C compiler and build system, but it isn't planned to be a drop-in replacement C compiler like `tcc` because we also take on responsibility of the build system.

The main benefit of this is faster compile-times and better whole-program optimizations, which would be lost if it used the same model of compiling each C file to an object file. Which is why it's planned to be so tightly integrated (it also gives better interoperability which is the main goal).

This of course is ambitious, and easier said than done, but would make working with C code as easy as just copying a few files while still having extremely fast compile times.
