### ISSUE TITLE
What is the current state of the C FFI?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#13]
Can I re-implement my Adept 2.x bindings by importing the C headers directly?

https://github.com/iahung2?tab=repositories

**Comment by IsaacShelton** [comment]
So far, support for header files is partially complete.

Around ~40% of constructs are implemented, but some headers work already such as `raylib.h`. For example:

main.adept
```
func main {
    screen_width i32 = 800
    screen_height i32 = 450

    InitWindow(screen_width, screen_height, c"Example Window!")

    while !WindowShouldClose() {
        BeginDrawing()

        ClearBackground(RAYWHITE)

        DrawText(c"Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY)

        EndDrawing()
    }

    CloseWindow()
}
```

This file compiles and gets all of the symbols it needs from the header (which even includes values from macros such as RAYWHITE and LIGHTGRAY)

The other main challenge though, is getting the C ABI working correctly for each architecture and os. Previously, passing struct values between Adept and C would not work correctly due to ABI incompatibility. This is what I'm working to fix right now, as the example raylib program has a red background when it should have a white background (ABI inconsistency is messing it up).

Unfortunately, correctly implementing the C ABI for each architecture/os is not simple and will require tens of thousands of lines of code. But once it works, yes you will be able to just drop a header file into your project and use it without bindings.

So for those bindings, you probably won't need to implement anything apart from saying which libraries to link to.

But yes, it's not done yet. Features are missing and many parts of the language are still being designed and are subject to change.
