### ISSUE TITLE
Yet another new language

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#3]
https://dada-lang.org/

p/s: I'm really curious what Adept 3.0 will look like!

**Comment by IsaacShelton** [comment]
That's definitely an interesting language

What I'm trying to aim for is hopefully something simpler. The most promising design so far is:
- Reference counting for memory management
   - With explicit `acyclic` keyword to allow self-referential types that are acyclic
   - As well as some kind of standard slotmap data structure (like array where elements can be deleted and are indexed by version and index, not just index like normal array) for when cyclic data is needed
   - Eventually with reference coalescing and other optimizations to hopefully eliminate a majority of the runtime costs
- Mutable vs immutable types (e.g. `String` is read only, `!String` can be modified, and mutability effects will be observed by other references)
  - Since it's not unique ownership based, this does mean that incorrectly written multithreaded code would suffer the same issues as in most languages, although that is probably a fine trade off
- Linear type system (redeclaring variables is allowed including of a different type, variables are allowed to drop their data before the end of scope if they are no longer needed)
- Support for sum types (easy support for tagged union types)
- Resources such as files don't need to be closed (they are closed automatically after last use)

There are a few other things that I want to work into it, but this is the core design right now.

**Comment by ghost** [comment]
> * Reference counting for memory management

If we give up on the ability to export code outside and focus solely on becoming a better language, do you still choose this memory management model?

**Comment by IsaacShelton** [comment]
If exporting code outside was not allowed, I still think reference counting would probably be slightly preferred, due to it:

- Being simple
- Having reliable "finalizers" (with GC you still have to manually close resources, since they are only freed based on memory pressure)

Although GC would become more of an option. The primary downsides of reference counting are:
- Performance
- Inability to have reference cycles

which I hope to solve the first issue with good optimizations, and I hope the second is rare enough to make using a separate data structure for it not to be a issue.

This would allow for the memory management to be simple, fast, and have deterministic finalizers, which means that for the most part, it will feel like a garbage collected language, expect you don't have to manually close/destroy resources (such as files, sockets, GPU objects, etc.).

Then, a vast majority of the time when you have self-referential data, you can assert that it's acyclic. For example, linked lists, trees, etc. are the same as in GC, you just have to promise the compiler that they aren't cyclic. (And if you do choose to violate it, the worst that happens is a memory leak which can be detected by runtime tooling)
