### ISSUE TITLE
Adept3x FFI

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#8]
What is your approach? It seems you are using a lightweight C parser to parse the C headers directly.

**Comment by IsaacShelton** [comment]
I had some ideas of relying on https://github.com/vickenty/lang-c for C parsing, but I think we might have to roll our own in order to have high quality integration.

We might start with just simple headers first, and then expand to support more of the C standard, and then maybe an entire specialized C compiler (which would be faster and integrate better) depending on how well it works.

**Comment by ghost** [comment]
As Adept is already using LLVM, what do you think about using `libclang`?

**Comment by IsaacShelton** [comment]
`libclang` would be something interesting to consider yes. It is extremely large (hundreds of megabytes) which is not ideal but it definitely would make parsing (and potentially compilation at some point) a lot easier. It might be something to check out yes.

There is also the C++ question if `libclang` gets involved. I'm thinking that adding/maintaining entire support for C++ libraries is probably infeasible, so `libclang` might be good to start but may become overkill at some point, not sure yet. A subset of C++ could become supported at some point though. Of course this is still speculative.

I really think favoring tight integration would prove beneficial, so C/C++ files wouldn't be compiled as true C/C++, but rather adopted into the same translation pipeline as the regular adept code. This would allow for better interoperability, better cross-compilation support, and would give the freedom to do additional optimization things such as inlining and whole-program optimizations, and better compile times. Also, LLVM could be optional, and C/C++ code could potentially even be run at compile-time.

Which ever way is chosen it will probably be a big undertaking
